sudo: false
language: rust

os:
  - osx
  - linux

rust:
  - stable
  - nightly
  - 1.13.0

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$HOME/Library/Python/2.7/bin:$PATH

script:
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only nightly doc

after_success:
  - '[ $TRAVIS_OS_NAME = linux ] && travis-cargo --only nightly doc-upload'
  - travis-cargo coveralls --no-sudo

env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
