[package]
name = "snif"
version = "0.1.0"
authors = ["Matt <young.qubit@gmail.com>"]

[[bin]]
name = "snif"
test = false
doc = false

[dependencies]
interfaces = "0.0.3"
pnet = "*"
pnet_datalink = "0.20.0"
ipnetwork = "*"
clap = "2.29"
